#!/usr/bin/env python3
"""
Integration test for synthetic-adsb -> tracker-host -> retina-tracker pipeline.

This test validates that the retina-tracker correctly detects anomalous data
generated by synthetic-adsb, including:
- Supersonic aircraft (Mach 2-5)
- Instant direction changes
- Instant acceleration/deceleration
- Aircraft with and without ADS-B

Issue #6: Make synthetic data streamer with anomalies (w and w/o ADS-B)
"""

import json
import math
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "synthetic-adsb"))

from tracker.track_detections import (
    Tracker,
    set_config,
    get_config,
    MACH_1_MS,
    SPEED_OF_LIGHT,
)

import random

from motion_patterns import (
    CircularMotion,
    SupersonicLinearMotion,
    InstantDirectionChangeMotion,
    InstantAccelerationMotion,
    SupersonicDirectionChangeMotion,
    SupersonicAccelerationMotion,
)


TX_LAT = -34.9810
TX_LON = 138.7081
TX_ALT = 750
FC_HZ = 204.64e6

RX_CONFIG = {
    "lat": -34.9192,
    "lon": 138.6027,
    "alt": 110,
}


def haversine_distance(lat1, lon1, alt1, lat2, lon2, alt2):
    """Calculate 3D distance between two points."""
    lat1_r, lon1_r = math.radians(lat1), math.radians(lon1)
    lat2_r, lon2_r = math.radians(lat2), math.radians(lon2)

    dlat = lat2_r - lat1_r
    dlon = lon2_r - lon1_r
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_r) * math.cos(lat2_r) * math.sin(dlon / 2) ** 2
    surface_dist = 2 * 6371000 * math.asin(math.sqrt(a))

    alt_diff = alt2 - alt1
    return math.sqrt(surface_dist**2 + alt_diff**2)


def calculate_bistatic_range(aircraft_lat, aircraft_lon, aircraft_alt_ft):
    """Calculate bistatic range (TX -> aircraft -> RX) in km."""
    aircraft_alt_m = aircraft_alt_ft * 0.3048

    tx_to_aircraft = haversine_distance(
        TX_LAT, TX_LON, TX_ALT, aircraft_lat, aircraft_lon, aircraft_alt_m
    )
    aircraft_to_rx = haversine_distance(
        aircraft_lat, aircraft_lon, aircraft_alt_m,
        RX_CONFIG["lat"], RX_CONFIG["lon"], RX_CONFIG["alt"]
    )

    return (tx_to_aircraft + aircraft_to_rx) / 1000.0


def calculate_doppler(velocity_knots):
    """Calculate Doppler shift from velocity."""
    velocity_ms = velocity_knots * 0.514444
    return velocity_ms * 2 * FC_HZ / SPEED_OF_LIGHT


def generate_detection_frame(aircraft_list, timestamp_ms, include_adsb=True):
    """
    Generate a detection frame from a list of aircraft.

    Args:
        aircraft_list: List of dicts with motion_pattern, altitude_ft, hex, gs_knots
        timestamp_ms: Timestamp in milliseconds
        include_adsb: Whether to include ADS-B data

    Returns:
        Detection frame dict compatible with retina-tracker
    """
    current_time = timestamp_ms / 1000.0

    delays = []
    dopplers = []
    snrs = []
    adsb_list = []

    for aircraft in aircraft_list:
        motion = aircraft["motion_pattern"]
        alt_ft = aircraft["altitude_ft"]
        icao_hex = aircraft["hex"]
        has_adsb = aircraft.get("has_adsb", True) and include_adsb

        lat, lon = motion.get_position(current_time)
        gs_knots = motion.get_velocity(current_time)
        track_deg = motion.get_heading(current_time)

        delay_km = calculate_bistatic_range(lat, lon, alt_ft)
        doppler_hz = calculate_doppler(gs_knots)

        delays.append(delay_km)
        dopplers.append(doppler_hz)
        snrs.append(15.0 + (hash(icao_hex) % 10))

        if has_adsb:
            adsb_list.append({
                "hex": icao_hex,
                "lat": lat,
                "lon": lon,
                "alt_baro": alt_ft,
                "gs": gs_knots,
                "track": track_deg,
            })
        else:
            adsb_list.append(None)

    return {
        "timestamp": timestamp_ms,
        "delay": delays,
        "doppler": dopplers,
        "snr": snrs,
        "adsb": adsb_list,
    }


def create_test_config():
    """Create tracker configuration for testing."""
    return {
        "tracker": {
            "m_threshold": 3,
            "n_window": 5,
            "n_delete": 10,
            "min_snr": 7.0,
            "gate_threshold": 15.0,
            "detection_window": 20,
        },
        "process_noise": {"delay": 0.1, "doppler": 0.5},
        "tracklet": {
            "max_delay_residual": 5.0,
            "max_doppler_residual": 50.0,
            "max_time_span": 5.0,
        },
        "adsb": {
            "enabled": True,
            "priority": True,
            "reference_location": {
                "latitude": RX_CONFIG["lat"],
                "longitude": RX_CONFIG["lon"],
                "altitude": RX_CONFIG["alt"],
            },
            "initial_covariance": {"position": 100.0, "velocity": 5.0},
        },
        "radar": {
            "center_frequency": FC_HZ,
        },
    }


class TestIntegrationSyntheticAnomalies:
    """Integration tests for synthetic anomaly detection."""

    def test_normal_aircraft_not_flagged(self):
        """Test that normal subsonic aircraft are NOT flagged as anomalous."""
        print("\n" + "=" * 70)
        print("Test: Normal Aircraft (subsonic) - should NOT be anomalous")
        print("=" * 70)

        config = create_test_config()
        set_config(config)

        start_time = time.time()
        motion = CircularMotion(
            center_lat=TX_LAT,
            center_lon=TX_LON,
            radius_deg=0.05,
            angular_speed=0.01,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 30000,
            "hex": "NORMAL1",
            "has_adsb": True,
        }]

        tracker = Tracker(config=config)

        for i in range(10):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms)

            delays = frame["delay"]
            dopplers = frame["doppler"]
            snrs = frame["snr"]
            adsb_list = frame["adsb"]

            detections = []
            for idx in range(len(delays)):
                det = {
                    "delay": delays[idx],
                    "doppler": dopplers[idx],
                    "snr": snrs[idx],
                }
                if adsb_list[idx]:
                    det["adsb"] = adsb_list[idx]
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: max_velocity={velocity_ms:.1f} m/s, "
                  f"is_anomalous={track.is_anomalous}")
            assert not track.is_anomalous, "Normal aircraft should NOT be flagged as anomalous"
            assert velocity_ms < MACH_1_MS, f"Normal aircraft velocity should be < Mach 1"

        print("PASSED: Normal aircraft not flagged as anomalous")

    def test_supersonic_aircraft_detected(self):
        """Test that supersonic aircraft (Mach 3) ARE flagged as anomalous."""
        print("\n" + "=" * 70)
        print("Test: Supersonic Aircraft (Mach 3) - SHOULD be anomalous")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        set_config(config)

        start_time = time.time()
        motion = SupersonicLinearMotion(
            start_lat=TX_LAT + 0.1,
            start_lon=TX_LON + 0.1,
            mach_number=3.0,
            direction_deg=45,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 50000,
            "hex": "SUPER01",
            "has_adsb": False,
        }]

        tracker = Tracker(config=config)

        for i in range(10):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms, include_adsb=False)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        found_anomalous = False
        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: max_velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), is_anomalous={track.is_anomalous}")

            if track.is_anomalous:
                found_anomalous = True
                assert velocity_ms > MACH_1_MS, "Anomalous track should have velocity > Mach 1"

        assert found_anomalous or len(confirmed) == 0, \
            "Supersonic aircraft should be flagged as anomalous (or no track formed)"

        if found_anomalous:
            print("PASSED: Supersonic aircraft correctly flagged as anomalous")
        else:
            print("NOTE: No track confirmed (fast object may not associate well)")

    def test_mixed_fleet_separation(self):
        """Test that mixed fleet correctly separates normal and anomalous tracks."""
        print("\n" + "=" * 70)
        print("Test: Mixed Fleet (1 normal + 1 supersonic)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 50.0
        set_config(config)

        start_time = time.time()

        normal_motion = CircularMotion(
            center_lat=TX_LAT,
            center_lon=TX_LON,
            radius_deg=0.05,
            angular_speed=0.01,
        )

        supersonic_motion = SupersonicLinearMotion(
            start_lat=TX_LAT + 0.2,
            start_lon=TX_LON + 0.2,
            mach_number=2.5,
            direction_deg=180,
            start_time=start_time,
        )

        aircraft = [
            {
                "motion_pattern": normal_motion,
                "altitude_ft": 30000,
                "hex": "NORMAL2",
                "has_adsb": True,
            },
            {
                "motion_pattern": supersonic_motion,
                "altitude_ft": 45000,
                "hex": "SUPER02",
                "has_adsb": False,
            },
        ]

        tracker = Tracker(config=config)

        for i in range(12):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                if frame["adsb"][idx]:
                    det["adsb"] = frame["adsb"][idx]
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        normal_tracks = [t for t in confirmed if not t.is_anomalous]
        anomalous_tracks = [t for t in confirmed if t.is_anomalous]

        print(f"  Normal tracks: {len(normal_tracks)}")
        print(f"  Anomalous tracks: {len(anomalous_tracks)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s, "
                  f"anomalous={track.is_anomalous}, adsb_hex={track.adsb_hex}")

        assert len(normal_tracks) >= 1, "Should have at least 1 normal track"
        print("PASSED: Mixed fleet correctly processed")

    def test_instant_direction_change_aircraft(self):
        """Test aircraft with instant direction changes."""
        print("\n" + "=" * 70)
        print("Test: Instant Direction Change Aircraft")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 30.0
        set_config(config)

        start_time = time.time()
        motion = InstantDirectionChangeMotion(
            start_lat=TX_LAT,
            start_lon=TX_LON + 0.1,
            velocity_knots=500,
            initial_direction_deg=0,
            change_interval_sec=2.0,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 25000,
            "hex": "CHANGE1",
            "has_adsb": True,
        }]

        tracker = Tracker(config=config)

        for i in range(15):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                if frame["adsb"][idx]:
                    det["adsb"] = frame["adsb"][idx]
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s, "
                  f"anomalous={track.is_anomalous}")

        print("PASSED: Instant direction change aircraft processed")

    def test_instant_acceleration_aircraft(self):
        """Test aircraft with instant acceleration/deceleration."""
        print("\n" + "=" * 70)
        print("Test: Instant Acceleration Aircraft")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 40.0
        set_config(config)

        start_time = time.time()
        speed_profile = [
            (2.0, 400),
            (1.5, 0),
            (2.0, 600),
            (2.0, 300),
        ]

        motion = InstantAccelerationMotion(
            start_lat=TX_LAT - 0.1,
            start_lon=TX_LON,
            direction_deg=90,
            speed_profile=speed_profile,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 20000,
            "hex": "ACCEL01",
            "has_adsb": True,
        }]

        tracker = Tracker(config=config)

        for i in range(20):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                if frame["adsb"][idx]:
                    det["adsb"] = frame["adsb"][idx]
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s, "
                  f"anomalous={track.is_anomalous}")

        print("PASSED: Instant acceleration aircraft processed")

    def test_supersonic_without_adsb(self):
        """Test that supersonic aircraft WITHOUT ADS-B are flagged as anomalous."""
        print("\n" + "=" * 70)
        print("Test: Supersonic WITHOUT ADS-B - MUST be anomalous")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        config["adsb"]["enabled"] = False
        set_config(config)

        start_time = time.time()
        motion = SupersonicLinearMotion(
            start_lat=TX_LAT,
            start_lon=TX_LON + 0.15,
            mach_number=4.0,
            direction_deg=270,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 55000,
            "hex": "STEALTH",
            "has_adsb": False,
        }]

        tracker = Tracker(config=config)

        for i in range(10):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms, include_adsb=False)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), anomalous={track.is_anomalous}")

            if velocity_ms > MACH_1_MS:
                assert track.is_anomalous, \
                    "Supersonic aircraft WITHOUT ADS-B MUST be flagged as anomalous"

        print("PASSED: Supersonic without ADS-B handled correctly")

    def test_supersonic_with_direction_changes(self):
        """Test combined anomaly: supersonic speed + instant direction changes."""
        print("\n" + "=" * 70)
        print("Test: Combined Anomaly - Supersonic + Direction Changes (Issue #6: 1+2)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        set_config(config)

        start_time = time.time()
        motion = SupersonicDirectionChangeMotion(
            start_lat=TX_LAT,
            start_lon=TX_LON + 0.1,
            mach_number=2.5,
            initial_direction_deg=0,
            change_interval_sec=2.0,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 50000,
            "hex": "COMBO12",
            "has_adsb": False,
        }]

        tracker = Tracker(config=config)

        for i in range(15):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms, include_adsb=False)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), anomalous={track.is_anomalous}")

            if velocity_ms > MACH_1_MS:
                assert track.is_anomalous, \
                    "Supersonic + direction change should be flagged as anomalous"

        print("PASSED: Supersonic + direction change aircraft handled correctly")

    def test_supersonic_with_acceleration(self):
        """Test combined anomaly: supersonic speeds + instant acceleration/standstill."""
        print("\n" + "=" * 70)
        print("Test: Combined Anomaly - Supersonic + Acceleration (Issue #6: 1+3)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        set_config(config)

        start_time = time.time()
        speed_profile_mach = [
            (2.0, 3.0),
            (1.5, 0),
            (2.0, 4.0),
            (2.0, 2.0),
        ]

        motion = SupersonicAccelerationMotion(
            start_lat=TX_LAT - 0.1,
            start_lon=TX_LON,
            direction_deg=90,
            speed_profile_mach=speed_profile_mach,
            start_time=start_time,
        )

        aircraft = [{
            "motion_pattern": motion,
            "altitude_ft": 55000,
            "hex": "COMBO13",
            "has_adsb": False,
        }]

        tracker = Tracker(config=config)

        for i in range(20):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms, include_adsb=False)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        found_supersonic = False
        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), anomalous={track.is_anomalous}")

            if velocity_ms > MACH_1_MS:
                found_supersonic = True
                assert track.is_anomalous, \
                    "Supersonic + acceleration should be flagged as anomalous"

        print("PASSED: Supersonic + acceleration aircraft handled correctly")

    def test_inaccurate_adsb_spoofing(self):
        """Test inaccurate ADS-B: reports subsonic but actually supersonic (spoofing)."""
        print("\n" + "=" * 70)
        print("Test: Inaccurate ADS-B - Subsonic broadcast but supersonic Doppler")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        set_config(config)

        start_time = time.time()
        motion = SupersonicLinearMotion(
            start_lat=TX_LAT,
            start_lon=TX_LON + 0.1,
            mach_number=3.0,
            direction_deg=45,
            start_time=start_time,
        )

        tracker = Tracker(config=config)

        for i in range(10):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            current_time = timestamp_ms / 1000.0

            lat, lon = motion.get_position(current_time)
            actual_gs_knots = motion.get_velocity(current_time)
            track_deg = motion.get_heading(current_time)

            delay_km = calculate_bistatic_range(lat, lon, 50000)
            doppler_hz = calculate_doppler(actual_gs_knots)

            fake_gs_knots = 350

            detections = [{
                "delay": delay_km,
                "doppler": doppler_hz,
                "snr": 18.0,
                "adsb": {
                    "hex": "SPOOF01",
                    "lat": lat,
                    "lon": lon,
                    "alt_baro": 50000,
                    "gs": fake_gs_knots,
                    "track": track_deg,
                },
            }]

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), anomalous={track.is_anomalous}")
            print(f"    ADS-B reported: 350 knots (~180 m/s), Actual Doppler implies: {velocity_ms:.1f} m/s")

            assert track.is_anomalous, \
                "Spoofed ADS-B (subsonic) with supersonic Doppler MUST be flagged as anomalous"

        print("PASSED: Inaccurate/spoofed ADS-B correctly detected as anomalous")

    def test_varying_snr_and_noise(self):
        """Test detection with varying SNR and added noise (realistic conditions)."""
        print("\n" + "=" * 70)
        print("Test: Varying SNR and Noise (realistic detection conditions)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 50.0
        config["tracker"]["min_snr"] = 8.0
        set_config(config)

        random.seed(42)
        start_time = time.time()

        normal_motion = CircularMotion(TX_LAT, TX_LON, 0.05, 0.01)
        supersonic_motion = SupersonicLinearMotion(
            TX_LAT + 0.15, TX_LON + 0.15, 2.5, 135, start_time
        )

        tracker = Tracker(config=config)

        for i in range(20):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            current_time = timestamp_ms / 1000.0

            detections = []

            lat1, lon1 = normal_motion.get_position(current_time)
            gs1 = normal_motion.get_velocity(current_time)
            delay1 = calculate_bistatic_range(lat1, lon1, 30000)
            doppler1 = calculate_doppler(gs1)

            delay1 += random.gauss(0, 0.5)
            doppler1 += random.gauss(0, 10)
            snr1 = random.uniform(10, 25)

            detections.append({
                "delay": delay1,
                "doppler": doppler1,
                "snr": snr1,
                "adsb": {
                    "hex": "NOISY01",
                    "lat": lat1,
                    "lon": lon1,
                    "alt_baro": 30000,
                    "gs": gs1,
                    "track": normal_motion.get_heading(current_time),
                },
            })

            lat2, lon2 = supersonic_motion.get_position(current_time)
            gs2 = supersonic_motion.get_velocity(current_time)
            delay2 = calculate_bistatic_range(lat2, lon2, 50000)
            doppler2 = calculate_doppler(gs2)

            delay2 += random.gauss(0, 1.0)
            doppler2 += random.gauss(0, 20)
            snr2 = random.uniform(8, 20)

            detections.append({
                "delay": delay2,
                "doppler": doppler2,
                "snr": snr2,
            })

            if random.random() < 0.3:
                detections.append({
                    "delay": random.uniform(20, 150),
                    "doppler": random.uniform(-500, 500),
                    "snr": random.uniform(7, 12),
                })

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        normal_count = 0
        anomalous_count = 0
        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            status = "ANOMALOUS" if track.is_anomalous else "normal"
            print(f"  [{status}] Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s, "
                  f"assoc={track.n_associated}")

            if track.is_anomalous:
                anomalous_count += 1
            else:
                normal_count += 1

        assert len(confirmed) >= 1, "Should track at least 1 aircraft through noise"
        print(f"PASSED: Tracked {normal_count} normal, {anomalous_count} anomalous through noise")

    def test_missed_detections(self):
        """Test tracking continuity with missed detections (detection gaps)."""
        print("\n" + "=" * 70)
        print("Test: Missed Detections (gaps in detection stream)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 50.0
        config["tracker"]["n_delete"] = 8
        set_config(config)

        random.seed(42)
        start_time = time.time()

        motion = CircularMotion(TX_LAT, TX_LON, 0.05, 0.01)

        tracker = Tracker(config=config)

        for i in range(30):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            current_time = timestamp_ms / 1000.0

            miss_prob = 0.3
            if random.random() < miss_prob:
                tracker.process_frame([], timestamp_ms)
                continue

            lat, lon = motion.get_position(current_time)
            gs = motion.get_velocity(current_time)
            delay = calculate_bistatic_range(lat, lon, 30000)
            doppler = calculate_doppler(gs)

            detections = [{
                "delay": delay,
                "doppler": doppler,
                "snr": 15.0,
                "adsb": {
                    "hex": "GAPPY01",
                    "lat": lat,
                    "lon": lon,
                    "alt_baro": 30000,
                    "gs": gs,
                    "track": motion.get_heading(current_time),
                },
            }]

            tracker.process_frame(detections, timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            continuity = track.n_associated / max(track.n_frames, 1)
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s, "
                  f"assoc={track.n_associated}, frames={track.n_frames}, "
                  f"continuity={continuity:.1%}")

        assert len(confirmed) >= 1, "Should maintain track despite missed detections"
        print("PASSED: Track maintained through missed detections")

    def test_intermittent_adsb(self):
        """Test aircraft with ADS-B present only some fraction of the time."""
        print("\n" + "=" * 70)
        print("Test: Intermittent ADS-B (present ~30% of time)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 100.0
        set_config(config)

        random.seed(42)
        start_time = time.time()

        motion = SupersonicLinearMotion(
            TX_LAT, TX_LON + 0.1, 2.0, 90, start_time
        )

        tracker = Tracker(config=config)
        adsb_probability = 0.3

        frames_with_adsb = 0
        frames_without_adsb = 0

        for i in range(20):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            current_time = timestamp_ms / 1000.0

            lat, lon = motion.get_position(current_time)
            gs_knots = motion.get_velocity(current_time)
            track_deg = motion.get_heading(current_time)

            delay = calculate_bistatic_range(lat, lon, 50000)
            doppler = calculate_doppler(gs_knots)

            det = {
                "delay": delay,
                "doppler": doppler,
                "snr": 18.0,
            }

            if random.random() < adsb_probability:
                det["adsb"] = {
                    "hex": "INTERM1",
                    "lat": lat,
                    "lon": lon,
                    "alt_baro": 50000,
                    "gs": gs_knots,
                    "track": track_deg,
                }
                frames_with_adsb += 1
            else:
                frames_without_adsb += 1

            tracker.process_frame([det], timestamp_ms)

        confirmed = tracker.get_confirmed_tracks()
        print(f"Confirmed tracks: {len(confirmed)}")
        print(f"  Frames with ADS-B: {frames_with_adsb}, without: {frames_without_adsb}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            print(f"  Track {track.id or 'unnamed'}: velocity={velocity_ms:.1f} m/s "
                  f"({velocity_ms/MACH_1_MS:.1f} Mach), anomalous={track.is_anomalous}, "
                  f"adsb_hex={track.adsb_hex}")

            assert track.is_anomalous, \
                "Supersonic aircraft with intermittent ADS-B should still be flagged"

        print("PASSED: Intermittent ADS-B handled correctly - anomaly still detected")

    def test_full_pipeline_simulation(self):
        """
        Full pipeline simulation: multiple aircraft types over extended period.
        This simulates what tracker-host would feed to retina-tracker.
        """
        print("\n" + "=" * 70)
        print("Test: Full Pipeline Simulation (30 seconds, mixed fleet)")
        print("=" * 70)

        config = create_test_config()
        config["tracker"]["gate_threshold"] = 50.0
        set_config(config)

        start_time = time.time()

        normal1 = CircularMotion(TX_LAT, TX_LON, 0.05, 0.01)
        normal2 = CircularMotion(TX_LAT + 0.1, TX_LON - 0.1, 0.03, -0.015)
        supersonic = SupersonicLinearMotion(
            TX_LAT - 0.2, TX_LON + 0.2, 2.0, 120, start_time
        )
        direction_change = InstantDirectionChangeMotion(
            TX_LAT + 0.15, TX_LON + 0.15, 450, 45, 4.0, start_time
        )

        aircraft = [
            {"motion_pattern": normal1, "altitude_ft": 32000, "hex": "AAL123", "has_adsb": True},
            {"motion_pattern": normal2, "altitude_ft": 28000, "hex": "UAL456", "has_adsb": True},
            {"motion_pattern": supersonic, "altitude_ft": 60000, "hex": "UNKN01", "has_adsb": False},
            {"motion_pattern": direction_change, "altitude_ft": 22000, "hex": "WEIRD1", "has_adsb": True},
        ]

        tracker = Tracker(config=config)
        frame_count = 60

        for i in range(frame_count):
            timestamp_ms = int((start_time + i * 0.5) * 1000)
            frame = generate_detection_frame(aircraft, timestamp_ms)

            detections = []
            for idx in range(len(frame["delay"])):
                det = {
                    "delay": frame["delay"][idx],
                    "doppler": frame["doppler"][idx],
                    "snr": frame["snr"][idx],
                }
                if frame["adsb"][idx]:
                    det["adsb"] = frame["adsb"][idx]
                detections.append(det)

            tracker.process_frame(detections, timestamp_ms)

            if (i + 1) % 20 == 0:
                active = tracker.get_active_tracks()
                print(f"  Frame {i + 1}/{frame_count}: {len(active)} active tracks")

        confirmed = tracker.get_confirmed_tracks()
        normal_tracks = [t for t in confirmed if not t.is_anomalous]
        anomalous_tracks = [t for t in confirmed if t.is_anomalous]

        print(f"\nFinal Results:")
        print(f"  Total confirmed tracks: {len(confirmed)}")
        print(f"  Normal tracks: {len(normal_tracks)}")
        print(f"  Anomalous tracks: {len(anomalous_tracks)}")

        for track in confirmed:
            velocity_ms = track.max_velocity_ms
            status = "ANOMALOUS" if track.is_anomalous else "normal"
            print(f"  [{status}] Track {track.id or 'unnamed'}: "
                  f"velocity={velocity_ms:.1f} m/s, hex={track.adsb_hex}, "
                  f"assoc={track.n_associated}")

        assert len(confirmed) >= 1, "Should have at least 1 confirmed track"
        print("\nPASSED: Full pipeline simulation completed successfully")


def test_normal_aircraft_not_flagged():
    test = TestIntegrationSyntheticAnomalies()
    test.test_normal_aircraft_not_flagged()


def test_supersonic_aircraft_detected():
    test = TestIntegrationSyntheticAnomalies()
    test.test_supersonic_aircraft_detected()


def test_mixed_fleet_separation():
    test = TestIntegrationSyntheticAnomalies()
    test.test_mixed_fleet_separation()


def test_instant_direction_change_aircraft():
    test = TestIntegrationSyntheticAnomalies()
    test.test_instant_direction_change_aircraft()


def test_instant_acceleration_aircraft():
    test = TestIntegrationSyntheticAnomalies()
    test.test_instant_acceleration_aircraft()


def test_supersonic_without_adsb():
    test = TestIntegrationSyntheticAnomalies()
    test.test_supersonic_without_adsb()


def test_full_pipeline_simulation():
    test = TestIntegrationSyntheticAnomalies()
    test.test_full_pipeline_simulation()


def test_supersonic_with_direction_changes():
    test = TestIntegrationSyntheticAnomalies()
    test.test_supersonic_with_direction_changes()


def test_supersonic_with_acceleration():
    test = TestIntegrationSyntheticAnomalies()
    test.test_supersonic_with_acceleration()


def test_inaccurate_adsb_spoofing():
    test = TestIntegrationSyntheticAnomalies()
    test.test_inaccurate_adsb_spoofing()


def test_varying_snr_and_noise():
    test = TestIntegrationSyntheticAnomalies()
    test.test_varying_snr_and_noise()


def test_missed_detections():
    test = TestIntegrationSyntheticAnomalies()
    test.test_missed_detections()


def test_intermittent_adsb():
    test = TestIntegrationSyntheticAnomalies()
    test.test_intermittent_adsb()


if __name__ == "__main__":
    print("=" * 70)
    print("INTEGRATION TEST: Synthetic ADS-B -> Retina Tracker Anomaly Detection")
    print("=" * 70)

    tests = [
        test_normal_aircraft_not_flagged,
        test_supersonic_aircraft_detected,
        test_mixed_fleet_separation,
        test_instant_direction_change_aircraft,
        test_instant_acceleration_aircraft,
        test_supersonic_without_adsb,
        test_supersonic_with_direction_changes,
        test_supersonic_with_acceleration,
        test_inaccurate_adsb_spoofing,
        test_varying_snr_and_noise,
        test_missed_detections,
        test_intermittent_adsb,
        test_full_pipeline_simulation,
    ]

    passed = 0
    failed = 0

    for test_func in tests:
        try:
            test_func()
            passed += 1
        except AssertionError as e:
            print(f"\nFAILED: {test_func.__name__}")
            print(f"  Error: {e}")
            failed += 1
        except Exception as e:
            print(f"\nERROR: {test_func.__name__}")
            print(f"  Exception: {e}")
            import traceback
            traceback.print_exc()
            failed += 1

    print("\n" + "=" * 70)
    print(f"SUMMARY: {passed} passed, {failed} failed")
    print("=" * 70)

    sys.exit(0 if failed == 0 else 1)
